apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts
  labels:
    app: accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      labels:
        app: accounts
    spec:
      containers:
        - name: accounts
          image: image-registry.openshift-image-registry.svc:5000/sn-labs-sabrinaclark/accounts:1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: FLASK_APP
              value: service:app
            - name: FLASK_ENV
              value: production
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: uri
---
apiVersion: v1
kind: Service
metadata:
  name: accounts
  labels:
    app: accounts
spec:
  selector:
    app: accounts
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: accounts
spec:
  to:
    kind: Service
    name: accounts
  port:
    targetPort: 80
